apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: practice-cert
  namespace: anuj
spec:
  secretName: practice-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - "predictyourday.xyz"

