---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ramaa
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/prod/rama
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: rama
